repair usa case counts
epiforecasts/NCoVUtils pull request #69
Opened 2020-04-08 22:00 UTC by hamishgibbs

NYT changed to cumulative cases. I have removed cumsum and behaviour should be same as previous version of the function.

2020-04-08 23:13 UTC, hamishgibbs commented
I believe build failing because of slow url for `get_interventions_data`

2020-04-09 10:19 UTC, seabbs requested changes
Looks good. Just need to clarify a few things. Also seeing a build failure....

2020-04-09 10:19 UTC, seabbs commented on R/get_spain_regional_cases.R
> +                    hospital_daily = hospital_cum - lag(hospital_cum, default = dplyr::first(hospital_cum)),
Need to add `dplyr::lag` into the imports

2020-04-09 10:19 UTC, seabbs commented on R/get_us_regional_cases.R
> +    cases <- mem_read(path) %>%
Is this the same as cases - lag(cases)?

2020-04-09 10:19 UTC, seabbs commented on R/get_us_regional_cases.R
> +    cases <- mem_read(path) %>%
Do you think it is a good idea to have cumulative as an argument?

2020-04-09 10:19 UTC, seabbs commented on tests/testthat/custom_tests/expect_colname.R
> +expect_colname <- function(expected_colname, colnames){
NIce

2020-04-09 10:19 UTC, seabbs commented on tests/testthat/test-get_belgium_regional_cases.R
> +test_that("get_belgium_regional_cases data sources are unchanged", {
Nice :)

2020-04-10 11:43 UTC, closed without merging