Update README.md
epiforecasts/NCoVUtils pull request #83
Opened 2020-04-13 11:29 UTC by kathsherratt

2020-04-13 11:55 UTC, ffinger requested changes
Looks good to me, some comments on the wording.

2020-04-13 11:55 UTC, ffinger commented on README.md
> +1. Extract total global cases and deaths by country using:
what is the source of the data for the `get_total_cases` function?

2020-04-13 11:55 UTC, ffinger commented on README.md
> +2. Extract international case counts compiled by the WHO using:
```suggestion
2. Extract daily international case and death counts compiled by the WHO using:
```

2020-04-13 11:55 UTC, ffinger commented on README.md
> +3. Extract international case counts compiled by ECDC using:
```suggestion
3. Extract daily international case and death counts compiled by ECDC using:
```

2020-04-13 11:55 UTC, ffinger commented on README.md
> +We currently have functions to extract sub-national level data for 11 countries. These are typically at the admin-1 level, the largest regions available. We are also working on joining the data to st
I wouldn't put the number of countries, we will forget to update it.

2020-04-13 11:55 UTC, ffinger commented on README.md
> +We currently have functions to extract sub-national level data for 11 countries. These are typically at the admin-1 level, the largest regions available. We are also working on joining the data to st
```suggestion
We currently have functions to extract sub-national level data for 11 countries. These are at the most detailed subdivision level available, typically adm1 (provinces, regions, states or similar). We are also working on adding standard georeferencing codes to allow easy mapping.
```

2020-04-13 11:55 UTC, ffinger commented on README.md
> +For most countries, subnational cases can be extracted by using the following:
I wouldn't say this, there is too many exceptions...
Maybe we should work on a standardized interface and/or a wrapper function that takes "country" as an argument and calls the respective function.

2020-04-13 11:55 UTC, ffinger commented on README.md
> +We are working to include more countries.
```suggestion
We are working to include more countries.
Contributions via Pull Request are most welcome.
```

2020-04-13 18:55 UTC, ffinger commented on README.md
> +For most countries, subnational cases can be extracted by using the following:
> Maybe we should work on a standardized interface and/or a wrapper function that takes "country" as an argument and calls the respective function.

Added an issue for this.

2020-04-24 17:12 UTC, seabbs approved these changes
Looks good

2020-04-24 17:16 UTC, seabbs approved these changes

2020-04-26 10:17 UTC, ffinger reviewed
Very minor requests, feel free to ignore.

2020-04-26 10:17 UTC, ffinger commented on README.md
> +There are three sources of worldwide, country-level data on cases and deaths.
I see only two? There is three functions but two sources?

2020-04-26 10:17 UTC, ffinger commented on README.md
>  ## Development
maybe add sentence that help is appreciated, see issues? or describe some domains where help is appreciated (new data sources, geo-coding, ....)?

2020-04-26 10:18 UTC, ffinger approved these changes

2020-04-29 12:14 UTC, kathsherratt commented
Thanks very much for reviewing twice Flavio (I'm sorry for taking a long time earlier to update this). I've included the new comments so this should be ready to go. Thanks again!

2020-04-29 13:25 UTC, ffinger commented
There seems to be a build failure in the tests, but nothing to do in with the readme.

2020-04-29 13:25 UTC, merged